# Generated by Django 3.2.6 on 2021-08-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210810_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
